#ifndef COMMON_H
#define COMMON_H

#include "version.h"

#ifdef WE_PIC
#include "WE/wepiclib.h"
#endif
#ifdef WE_DBUS
#include "WE/wedbuslib.h"
#include "CustomWidgets/switch.h"
#endif
#ifdef WE_WDT
#include "watchdog.h"
#endif




#define SW_NAME     "Pellet Controller"

/* Version, git commit and build time: version.h, generated by version.pri */
#define SW_VER      PC_VERSION
#define SW_NAME_VER      SW_NAME " - " SW_VER



#define BUFFSIZE                (256*1024)
#define BASH_PATH               "/bin/bash"

#endif // COMMON_H
